-- begin AUTODEALER_CAR
alter table AUTODEALER_CAR add constraint FK_AUTODEALER_CAR_CAR_MODEL_ID foreign key (CAR_MODEL_ID) references AUTODEALER_CAR_MODEL(ID)^
alter table AUTODEALER_CAR add constraint FK_AUTODEALER_CAR_CARD_ID foreign key (CARD_ID) references DF_DOC(CARD_ID)^
create index IDX_AUTODEALER_CAR_CAR_MODEL on AUTODEALER_CAR (CAR_MODEL_ID)^
-- end AUTODEALER_CAR
-- begin AUTODEALER_PURCHASE_REQUEST
alter table AUTODEALER_PURCHASE_REQUEST add constraint FK_AUTODEALER_PURCHASE_REQUEST_CAR_ID foreign key (CAR_ID) references AUTODEALER_CAR(CARD_ID)^
alter table AUTODEALER_PURCHASE_REQUEST add constraint FK_AUTODEALER_PURCHASE_REQUEST_BUYER_ID foreign key (BUYER_ID) references DF_CONTRACTOR(CORRESPONDENT_ID)^
alter table AUTODEALER_PURCHASE_REQUEST add constraint FK_AUTODEALER_PURCHASE_REQUEST_BANK_ID foreign key (BANK_ID) references DF_BANK(ID)^
alter table AUTODEALER_PURCHASE_REQUEST add constraint FK_AUTODEALER_PURCHASE_REQUEST_CARD_ID foreign key (CARD_ID) references DF_DOC(CARD_ID)^
create index IDX_AUTODEALER_PURCHASE_REQUEST_BUYER on AUTODEALER_PURCHASE_REQUEST (BUYER_ID)^
create index IDX_AUTODEALER_PURCHASE_REQUEST_CAR on AUTODEALER_PURCHASE_REQUEST (CAR_ID)^
create index IDX_AUTODEALER_PURCHASE_REQUEST_BANK on AUTODEALER_PURCHASE_REQUEST (BANK_ID)^
-- end AUTODEALER_PURCHASE_REQUEST
